default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: invoice
  password: smbusiness

development:
  <<: *default
  database: invoice_api_dev

test:
  <<: *default
  database: invoice_api_test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: invoice_api
