# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8de975e44c43440fd0a4e206ac06d4c14b4531a0e07163fdab9a6915eee5e54977a19bceb95e3a5e6be5983a71a9d8d20fbbf6fa02779cc010ddca3faa3b7bac

test:
  secret_key_base: 29c04c3ed5ac0a520dd3351fe2b54eef4cc3e6381e8459546a7efbfc0ba00ce9b40c4589973dc92e28c16f3ce86b109f8687401af6b877ee7def2c236bd56613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
